//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.01.30 at 09:31:06 PM MST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://example.com/purchase", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.schemaexample.jaxb9.domain;
